-- This will wipe the old table and create a fresh one with safe column names
DROP TABLE IF EXISTS bookings;

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quarter_qty INTEGER DEFAULT 0,
  half_qty INTEGER DEFAULT 0,
  full_qty INTEGER DEFAULT 0,
  total NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Re-enable security
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous inserts" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous select" ON bookings FOR SELECT USING (true);
