-- This will wipe the old tables and create fresh ones
DROP TABLE IF EXISTS booking_controls;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  name TEXT NOT NULL,
  animal_type TEXT NOT NULL DEFAULT 'cow',
  quarter_qty INTEGER DEFAULT 0,
  half_qty INTEGER DEFAULT 0,
  full_qty INTEGER DEFAULT 0,
  subtotal NUMERIC,
  service_fee NUMERIC,
  total NUMERIC NOT NULL,
  second_account_note TEXT DEFAULT 'UBA - 2233156875',
  email TEXT NOT NULL,
  payment_status TEXT DEFAULT 'pending',
  payment_proof TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE booking_controls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cow_open BOOLEAN NOT NULL DEFAULT TRUE,
  ram_open BOOLEAN NOT NULL DEFAULT TRUE,
  goat_open BOOLEAN NOT NULL DEFAULT TRUE,
  cow_price NUMERIC NOT NULL DEFAULT 13000,
  ram_price NUMERIC NOT NULL DEFAULT 25000,
  goat_price NUMERIC NOT NULL DEFAULT 25000,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO booking_controls (cow_open, ram_open, goat_open, cow_price, ram_price, goat_price) VALUES (TRUE, TRUE, TRUE, 13000, 25000, 25000);

-- Re-enable security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_controls ENABLE ROW LEVEL SECURITY;

-- Simple policies for demonstration (In production, these should be more restrictive)
CREATE POLICY "Allow anonymous inserts" ON users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous select" ON users FOR SELECT USING (true);
CREATE POLICY "Allow anonymous inserts" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous select" ON bookings FOR SELECT USING (true);
CREATE POLICY "Allow anonymous inserts" ON booking_controls FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous select" ON booking_controls FOR SELECT USING (true);
CREATE POLICY "Allow anonymous updates" ON booking_controls FOR UPDATE USING (true);
